### PR TITLE
Always show target hadoop environment and current time in UTC in the …

### PR DESCRIPTION
**Pull request by rdhallman**
…output of Hodor commands.

@hal-henningsmoen very simple change, to just show "water" or "samurai" in Hodor's output. Please review and merge.

### CODE REVIEW

**Comment by hal-henningsmoen** [comment]
Problem with ruby version defined in Travis being before ruby version define for project.  Could fix by changing Travis setting. Looks like you can use ruby-head in travis.yml file.  Would that be the approach you want to take?

**Comment by hal-henningsmoen** [comment]
LGTM other than broken build.

**Comment by apicker** [comment]
Sometimes local time is a very useful piece of info. Anyway to make it optional via a '--localtime' flag?

**Comment by rdhallman** [comment]
@apicker Yes, either a --localtime flag or possibly display the time in both UTC and Local. Let me think about that one and get back to you.

**Comment by rdhallman** [comment]
@hal-henningsmoen I didn't setup the original travis.yml file, so if is using ruby-head I wasn't aware of that. I'll update the travis.yml file and see if I can resolve the build failure.

**Comment by hal-henningsmoen** [comment]
Travis is using 2.2.1 I think and  the ruby.version file is ruby-2.2-head
Not sure if Travis allows ruby-2.2-head might have to just do ruby-head or something similar.

**Pull request merged**
